### PR TITLE
Updated README.md in Japanese

### PR DESCRIPTION
**Pull request by nishiku**
I updated Japanese README.md.

### CODE REVIEW

**Comment by ThomasVon2021** [comment]
Thanks, the docs link: https://wiki.blicube.com/blikvm/en/. The docs Github link: https://github.com/ThomasVon2021/blikvm-site. I don't know if you are willing to translate the Japanese documents for this. I am willing to provide you with the hardware of blikvm that you are interested in as a gift.

**Comment by nishiku** [comment]
I will do that.

**Comment by ThomasVon2021** [comment]
Thank you very much. I will specifically thank you in the project. If you have the hardware you hope to get, I will try to provide it to you for free.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThomasVon2021/pikvm-board"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThomasVon2021/pikvm-board] Updated README.md in Japanese (PR #35)





 
I will do that.

**Comment by nishiku** [comment]
I forked blikvm-site repo, and I'll look into this ASAP. 

> If you have the hardware you hope to get, I will try to provide it to you for free.

Thanks. Could I have HAT version?

**Comment by ThomasVon2021** [comment]
Yes, please let me know when you start the formal document translation, and I will send you hat




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Masao ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 晚上6:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ThomasVon2021/pikvm-board] Updated README.md in Japanese (PR #35)






我做了网站回购，我会尽快调查的

如果你有你希望得到的硬件，我会尽量免费提供给你。

谢了。可以给我HAT版本吗？

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by nishiku** [comment]
I could prepare the environment to translate. I would like to do in my spare time.
スクリーンショット 2022-08-22 5 55 01

**Comment by ThomasVon2021** [comment]
Wow, thank you very much for taking your time to participate in the Japanese translation of blikvm documents. Please tell me your address and I will arrange to send you the hat version later. Which color do you prefer, black or blue.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThomasVon2021/pikvm-board"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 凌晨4:57
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ThomasVon2021/pikvm-board] Updated README.md in Japanese (PR #35)





 
I could prepare the environment to translate. I would like to do in my spare time.

**Comment by nishiku** [comment]
Please send email to my mail address which is in 'git log'. Then I'll reply to your email address.

**Comment by nishiku** [comment]
Or please let me know your mail address.
I don't want to write my address here.

**Comment by ThomasVon2021** [comment]
***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Masao ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 晚上8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ThomasVon2021/pikvm-board] Updated README.md in Japanese (PR #35)






或者请让我知道你的邮件地址。
我不想在这里写我的地址。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Pull request merged**
